### ISSUE TITLE
Not working with http://mosaik.tv

### ISSUE THREAD

**Issue by ghost** [andr3jx/RTMPExploreX#2]
http://mosaik.tv

A dump of this site reveals this info

  rtmpte://178.33.47.133/vod/mosaiktv

however RtmpExploreX detects nothing from this site.

**Comment by andr3jx** [comment]
I don't plan to develop RTMPExploreX further. RTMPDumpHelper should be used as replacement.
In your case the problem is that the stream uses the RTMPTE protocol. RTMPT is transmitted in most case on port 80 or 443. So the stream is encapsulated within HTTP requests. This makes it hard to distinguish the stream from normal traffic and to forward it to rtmpsrv.
